# Generated by Django 6.0.5 on 2026-06-03 00:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('preset_name', models.CharField(blank=True, max_length=200)),
                ('theme', models.TextField()),
                ('lyrics', models.TextField(blank=True)),
                ('character_ref', models.CharField(max_length=500)),
                ('song_filename', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('delivered', 'Delivered'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('current_stage', models.CharField(blank=True, max_length=50)),
                ('failed_stage', models.CharField(blank=True, max_length=50)),
                ('error_detail', models.TextField(blank=True)),
                ('output_path', models.CharField(blank=True, max_length=1000)),
                ('suggested_caption', models.TextField(blank=True)),
                ('chain_task_id', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(max_length=50)),
                ('kind', models.CharField(max_length=50)),
                ('path', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='jobs.job')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
