# Generated by Django 6.0.5 on 2026-06-03 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='song_source',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
