# Generated by Django 6.0.5 on 2026-06-03 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_song_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='song_clip',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
