# Generated by Django 6.0.5 on 2026-06-03 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_job_song_clip'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='character_image',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
