# Generated by Django 6.0.5 on 2026-06-04 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_job_character_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='backup_character_image',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='job',
            name='backup_character_ref',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
