# Generated by Django 6.0.5 on 2026-06-04 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_job_backup_character_image_job_backup_character_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='mode',
            field=models.CharField(default='dance', max_length=16),
        ),
    ]
