# Generated by Django 6.0.5 on 2026-06-05 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_job_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='hook',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
