# Generated by Django 6.0.5 on 2026-06-05 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_job_hook'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='style',
            field=models.TextField(blank=True),
        ),
    ]
