# Generated by Django 6.0.5 on 2026-06-06 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_job_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='captions_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='job',
            name='motion',
            field=models.TextField(blank=True),
        ),
    ]
