# Generated by Django 6.0.5 on 2026-06-06 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_job_motion_captions'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='framing',
            field=models.CharField(default='full', max_length=16),
        ),
    ]
