# Generated by Django 6.0.5 on 2026-06-06 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_job_framing'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='drive_source',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
