# Generated by Django 6.0.5 on 2026-06-07 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_job_drive_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='character_lora',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='job',
            name='character_trigger',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
