# Generated by Django 6.0.5 on 2026-06-08 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_job_character_lora_job_character_trigger'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='lora_scale',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
