# Generated by Django 6.0.5 on 2026-06-08 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0013_job_lora_scale'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='scene_generator',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
