"""Preset loading + Job creation.

A preset is a YAML file describing one job: the song (audio + optional
lyrics), the theme prompt, and the locked character's identity asset. Loading
validates the shape and that referenced files exist (loud failures — a typo'd
path must not silently produce an empty video), then snapshots everything into
a ``Job`` row so a later edit to the preset file can't mutate an in-flight run.
"""

from __future__ import annotations

import shutil
from pathlib import Path

import yaml
from django.conf import settings

from core.audio import TimeRangeError, parse_timerange
from core.storage import job_dir
from jobs.models import Job


class PresetError(ValueError):
    """A preset is missing required fields or references missing files."""


def _require(mapping: dict, key: str, where: str) -> object:
    if key not in mapping or mapping[key] in (None, ""):
        raise PresetError(f"Preset {where} is missing required key {key!r}.")
    return mapping[key]


def _parse_character(block: object, where: str) -> tuple[str, str]:
    """Parse a character block into ``(character_ref, character_image)``.

    Exactly one of: ``image`` (a ready-made greenscreen portrait, used as-is and
    returned as both ref and image), ``description`` (text, generated by FLUX),
    or ``identity_asset`` (a file, returned as the ref).
    """
    if not isinstance(block, dict):
        raise PresetError(f"Preset '{where}' needs 'image', 'description', or 'identity_asset'.")
    chosen = [k for k in ("image", "description", "identity_asset") if block.get(k)]
    if len(chosen) != 1:
        raise PresetError(
            f"Preset '{where}' needs exactly one of 'image' (ready portrait), "
            "'description' (text), or 'identity_asset' (file)."
        )
    if block.get("image"):
        image_path = (settings.BASE_DIR / str(block["image"])).resolve()
        if not image_path.is_file():
            raise PresetError(f"Character image not found: {image_path}")
        return str(image_path), str(image_path)
    if block.get("identity_asset"):
        identity_path = (settings.BASE_DIR / str(block["identity_asset"])).resolve()
        if not identity_path.is_file():
            raise PresetError(f"Character identity asset not found: {identity_path}")
        return str(identity_path), ""
    return str(block["description"]).strip(), ""


def load_preset(path: str | Path) -> dict:
    """Parse + validate a preset YAML, returning a normalized dict.

    Keys: ``song.audio`` (path), ``song.lyrics`` (optional str), ``theme``
    (str), ``character.identity_asset`` (path).
    """
    preset_path = Path(path)
    if not preset_path.is_file():
        raise PresetError(f"Preset file not found: {preset_path}")
    data = yaml.safe_load(preset_path.read_text(encoding="utf-8"))
    if not isinstance(data, dict):
        raise PresetError(f"Preset {preset_path} did not parse to a mapping.")

    theme = _require(data, "theme", str(preset_path))

    mode = str(data.get("mode", "dance")).strip().lower()
    if mode not in {"dance", "closeup", "vibe"}:
        raise PresetError(
            f"{preset_path}: mode must be 'dance', 'closeup', or 'vibe', got {mode!r}."
        )

    # Dance mode generates the girl inside the scene, so a character block is
    # optional. Closeup mode lip-syncs a specific portrait, so it's required.
    if mode == "closeup":
        character: object = _require(data, "character", str(preset_path))
    else:
        character = data.get("character")

    # Vibe videos sync with nothing → they're MUTE: no song needed, no download.
    # (You add the TikTok sound at post time.) dance/closeup need a guide track.
    audio_path: Path | None = None
    source = None
    song = data.get("song")
    if mode != "vibe":
        if not isinstance(song, dict):
            raise PresetError("Preset 'song' must be a mapping with an 'audio' or 'source' key.")
        # Exactly one of a local file (``audio``) or a fetchable URL/query
        # (``source``). ``source`` is downloaded later, in prepare_assets.
        audio = song.get("audio")
        source = song.get("source")
        if bool(audio) == bool(source):
            raise PresetError(
                "Preset 'song' needs exactly one of 'audio' (path) or 'source' (url/query)."
            )
        if audio:
            audio_path = (settings.BASE_DIR / str(audio)).resolve()
            if not audio_path.is_file():
                raise PresetError(f"Song audio not found: {audio_path}")
    else:
        song = song if isinstance(song, dict) else {}

    if character:
        character_ref, character_image = _parse_character(character, "character")
    else:
        character_ref, character_image = "", ""

    # Optional backup character → trio layout. Absent = solo.
    backup_ref, backup_image = "", ""
    backup = data.get("backup")
    if backup:
        backup_ref, backup_image = _parse_character(backup, "backup")

    clip = str(song.get("clip")).strip() if song.get("clip") else ""
    if clip:
        # Validate the range now so a bad timestamp fails at submit, not mid-run.
        try:
            parse_timerange(clip)
        except TimeRangeError as exc:
            raise PresetError(str(exc)) from exc

    return {
        "audio_path": audio_path,
        "audio_source": (str(source).strip() if source else ""),
        "clip": clip,
        "mode": mode,
        "hook": (str(data.get("hook")).strip() if data.get("hook") else ""),
        "lyrics": (song.get("lyrics") or "").strip(),
        "theme": str(theme).strip(),
        "character_ref": character_ref,
        "character_image": character_image,
        "backup_character_ref": backup_ref,
        "backup_character_image": backup_image,
    }


def create_job_from_preset(preset_path: str | Path) -> Job:
    """Build a ``Job`` from a preset.

    A local ``song.audio`` is copied into the job dir now (self-contained run);
    a ``song.source`` (url/query) is stored and downloaded later by
    prepare_assets, so job creation stays cheap and offline.
    """
    preset = load_preset(preset_path)
    job = Job.objects.create(
        preset_name=str(preset_path),
        theme=preset["theme"],
        mode=preset["mode"],
        hook=preset["hook"],
        lyrics=preset["lyrics"],
        character_ref=preset["character_ref"],
        backup_character_ref=preset["backup_character_ref"],
        song_source=preset["audio_source"],
        song_clip=preset["clip"],
    )
    # Copy ready-made character images into the job dir so the run is
    # self-contained and immune to the source moving.
    for field, name, attr in (
        ("character_image", "character_source", "character_image"),
        ("backup_character_image", "backup_source", "backup_character_image"),
    ):
        if preset[field]:
            img_src = Path(preset[field])
            img_dest = job_dir(job.job_id) / f"{name}{img_src.suffix}"
            shutil.copyfile(img_src, img_dest)
            setattr(job, attr, str(img_dest))
            job.save(update_fields=[attr])
    src = preset["audio_path"]
    if src is not None:
        # Copy the local song into the job dir so the run is immune to the
        # source file moving/changing later.
        dest = job_dir(job.job_id) / f"source{src.suffix}"
        shutil.copyfile(src, dest)
        job.song_filename = str(dest)
        job.save(update_fields=["song_filename"])
    return job
