"""``manage.py describe_trend <url-or-path>`` — turn a trending clip into a
draft preset.

Watches the video with a ``VideoUnderstander`` (Gemini in real mode, a fixture
in fake mode) and writes a draft preset YAML with theme/style/motion/hook
filled in. The character and song are intentionally left as TODO comments — you
point the draft at a locked character (her gitignored LoRA) and pick the audio,
then run it. This is an *authoring* helper, NOT a pipeline stage: the runtime
still takes a finished preset in and produces a video out.
"""

from __future__ import annotations

import tempfile
from argparse import ArgumentParser
from pathlib import Path
from typing import Any

import yaml
from django.conf import settings
from django.core.management.base import BaseCommand, CommandError

from core.fetch import VideoFetchError, fetch_video
from providers.base import ProviderConfigError, get_video_understander


def _slug(source: str) -> str:
    stem = Path(source.split("?", 1)[0].rstrip("/")).stem or "trend"
    cleaned = "".join(ch if ch.isalnum() else "-" for ch in stem.lower()).strip("-")
    return cleaned or "trend"


def _timeline_lines(shots: list[dict[str, str]]) -> list[str]:
    """Render the second-by-second shot breakdown as a YAML comment block.

    The preset schema doesn't consume a timeline — the runtime reads only
    theme/style/motion/hook — so it lives as a comment: a reproduction spec the
    human (and the imitate-trend skill) reads to judge fidelity and tune the
    generation, without changing what the pipeline parses.
    """
    lines = ["# Timeline (reference — what to reproduce, second by second):"]
    for shot in shots:
        lines.append(f"#   {shot['time']}  {shot['action']}")
        lines.append(f"#       camera: {shot['camera']}")
    return lines


def _render_preset(source: str, mode: str, fields: dict[str, object]) -> str:
    """Build the draft preset text: a YAML body + TODO/timeline comment header.

    The structured fields are emitted via ``yaml.safe_dump`` (correct quoting);
    the character/song the human must still supply are prepended as comments, as
    is the shot-by-shot timeline (a reproduction reference the pipeline doesn't
    parse), so the draft documents everything without parsing to invalid values.
    """
    data: dict[str, Any] = {
        "mode": mode,
        "theme": str(fields["theme"]),
        "hook": str(fields["hook"]),
        "style": str(fields["style"]),
        "motion": str(fields["motion"]),
    }
    if mode == "mimic":
        data["drive"] = {"source": source}

    shots = fields.get("shots")
    header: list[str] = _timeline_lines(shots) + ["#"] if isinstance(shots, list) and shots else []
    header += [
        "# Draft preset generated by `manage.py describe_trend` from:",
        f"#   {source}",
        "# Review every field — the description is a starting point, not final.",
        "#",
        "# TODO: add the locked character (point at her gitignored local LoRA):",
        "# character:",
        '#   description: "the woman who performs this"',
        '#   lora: "presets/characters/neongirl.lora.safetensors"',
        '#   trigger: "neongirl"',
    ]
    if mode == "mimic":
        header += [
            "# mimic mode is mute — the drive clip below is the motion source; the",
            "# character above is REQUIRED. Add captions/sound at post.",
        ]
    else:
        header += [
            "# TODO: add the guide-track song:",
            "# song:",
            '#   source: "title artist"   # or a TikTok URL',
        ]

    body = yaml.safe_dump(data, sort_keys=False, allow_unicode=True, width=100)
    return "\n".join(header) + "\n\n" + body


class Command(BaseCommand):
    help = "Watch a trending video and write a draft preset (theme/style/motion/hook)."

    def add_arguments(self, parser: ArgumentParser) -> None:
        parser.add_argument("source", help="Trend video URL (TikTok/YouTube) or a local path.")
        parser.add_argument(
            "--mode",
            choices=["dance", "mimic"],
            default="dance",
            help="dance (recreate the vibe) or mimic (copy the exact moves; seeds drive.source).",
        )
        parser.add_argument(
            "--name", help="Slug for the preset filename (default: derived from the source)."
        )
        parser.add_argument(
            "--out", help="Write to this exact path instead of presets/trend_<name>.yaml."
        )

    def handle(self, *args: Any, **options: Any) -> None:
        source = options["source"]
        mode = options["mode"]

        if options.get("out"):
            out_path = Path(options["out"])
        else:
            name = options.get("name") or _slug(source)
            out_path = settings.BASE_DIR / "presets" / f"trend_{name}.yaml"

        with tempfile.TemporaryDirectory() as tmp:
            clip = Path(tmp) / "trend.mp4"
            try:
                fetch_video(source, clip)
            except VideoFetchError as exc:
                raise CommandError(str(exc)) from exc
            try:
                fields = get_video_understander().describe(clip)
            except ProviderConfigError as exc:
                raise CommandError(str(exc)) from exc

        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_path.write_text(_render_preset(source, mode, fields), encoding="utf-8")

        self.stdout.write(self.style.SUCCESS(f"Wrote draft preset: {out_path}"))
        self.stdout.write("Review it, fill in the character + song, then run with run_job.")
